# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Rails.co.za
url:   http://rails.co.za
author:
  name:    Gustav Paul      # For copyright notice and ATOM feeds
  email:   gustav@rails.co.za # Exception emails will go here, and it is used in ATOM feeds
  creds:
      - some-0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33 # username is 'some', password is 'foo'
